apiVersion: apps/v1
kind: Deployment
metadata:
  name: artificialfloat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artificialfloat
  template:
    metadata:
      labels:
        app: artificialfloat
    spec:
      containers:
        - name: artificialfloat
          image: gcr.io/gurlpower/artificialfloat-stedi-backend
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-prod
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-prod"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports: 
            - containerPort: 443
          resources:
            requests:
              cpu: 0.25
              memory: 250Mi
            limits:
              cpu: 0.5
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-artificial-float-nodeport
spec:
  selector:
    app: artificialfloat
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-artificial-float-certificate
spec:
  domains:
    - artificial-float.cit262.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-artificial-float-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stedi-artificial-float-public
    networking.gke.io/managed-certificates: stedi-artificial-float-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-artificial-float-nodeport
            port:
              number: 80
